services:
  investec-sync:
    build: .
    network_mode: "host"
    volumes:
      - ./data:/app/data
      - ${HOST_DIR:-.}:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production